[package]
name = "substrate-casper"
version = "0.1.0"
authors = ["Wei Tang <hi@that.world>"]
edition = "2018"

[dependencies]
primitives = { package = "substrate-primitives", git = "https://github.com/paritytech/substrate" }
sr-primitives = { git = "https://github.com/paritytech/substrate" }
consensus-common = { package = "substrate-consensus-common", git = "https://github.com/paritytech/substrate" }
client = { package = "substrate-client", git = "https://github.com/paritytech/substrate" }
casper-primitives = { package = "substrate-casper-primitives", path = "../primitives" }
log = { version = "0.4" }
