[package]
name = "substrate-casper"
version = "0.1.0"
authors = ["Wei Tang <hi@that.world>"]
edition = "2018"

[dependencies]
primitives = { package = "sp-core", git = "https://github.com/paritytech/substrate" }
sr-primitives = { package = "sp-runtime", git = "https://github.com/paritytech/substrate" }
consensus-common = { package = "sp-consensus", git = "https://github.com/paritytech/substrate" }
client = { package = "sc-client", git = "https://github.com/paritytech/substrate" }
client-db = { package = "sc-client-db", git = "https://github.com/paritytech/substrate" }
client-api = { package = "sc-client-api", git = "https://github.com/paritytech/substrate" }
casper-primitives = { package = "substrate-casper-primitives", path = "../primitives" }
log = { version = "0.4" }
