[workspace]
members = [
	"runtime",
	"primitives",
	"consensus",
	"crypto",
	"casper",
	"beacon",
	"blockchain",
	"blockchain/lmd-ghost",
	"yamltests",
	"utils/ssz",
	"utils/ssz-derive",
	"utils/ssz-merkle",
	"utils/keccak-hasher",
]
exclude = [
	"runtime/wasm",
]
