[workspace]
members = [
	"crypto",
	"beacon",
	"substrate",
	"substrate/runtime",
	"substrate/primitives",
	"substrate/consensus",
	"substrate/casper",
	"blockchain",
	"blockchain/common/rocksdb",
	"blockchain/lmd-ghost",
	"utils/codec-io",
	"utils/ssz",
	"utils/ssz-derive",
	"utils/keccak-hasher",
]
exclude = [
	"substrate/runtime/wasm",
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
