[workspace]
members = [
	"beacon",
	"yamltests",
	"substrate",
	"substrate/runtime",
	"substrate/primitives",
	"substrate/consensus",
	"substrate/crypto",
	"blockchain",
	"blockchain/lmd-ghost",
	"utils/ssz",
	"utils/ssz-derive",
	"utils/ssz-merkle",
]
exclude = [
	"runtime/wasm",
]
