[package]
name = "substrate-casper-node-template-runtime"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
safe-mix = { version = "1.0", default-features = false }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
rstd = { package = "sr-std", git = "https://github.com/paritytech/substrate", default_features = false }
runtime-io = { package = "sr-io", git = "https://github.com/paritytech/substrate", default_features = false }
version = { package = "sr-version", git = "https://github.com/paritytech/substrate", default_features = false }
support = { package = "srml-support", git = "https://github.com/paritytech/substrate", default_features = false }
primitives = { package = "substrate-primitives", git = "https://github.com/paritytech/substrate", default_features = false }
substrate-session = { git = "https://github.com/paritytech/substrate", default-features = false }
balances = { package = "srml-balances", git = "https://github.com/paritytech/substrate", default_features = false }
aura = { package = "srml-aura", git = "https://github.com/paritytech/substrate", default_features = false }
executive = { package = "srml-executive", git = "https://github.com/paritytech/substrate", default_features = false }
indices = { package = "srml-indices", git = "https://github.com/paritytech/substrate", default_features = false }
system = { package = "srml-system", git = "https://github.com/paritytech/substrate", default_features = false }
timestamp = { package = "srml-timestamp", git = "https://github.com/paritytech/substrate", default_features = false }
sudo = { package = "srml-sudo", git = "https://github.com/paritytech/substrate", default_features = false }
sr-primitives = { git = "https://github.com/paritytech/substrate", default_features = false }
client = { package = "substrate-client", git = "https://github.com/paritytech/substrate", default_features = false }
consensus-aura = { package = "substrate-consensus-aura-primitives", git = "https://github.com/paritytech/substrate", default_features = false }
offchain-primitives = { package = "substrate-offchain-primitives", git = "https://github.com/paritytech/substrate", default-features = false }
casper = { package = "srml-casper", path = "../../srml", default-features = false }
casper-primitives = { package = "substrate-casper-primitives", path = "../../primitives", default-features = false }
session = { package = "srml-session", git = "https://github.com/paritytech/substrate", default-features = false }
staking = { package = "srml-staking", git = "https://github.com/paritytech/substrate", default-features = false }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.2" }

[features]
default = ["std"]
std = [
	"codec/std",
	"client/std",
	"rstd/std",
	"runtime-io/std",
	"support/std",
	"balances/std",
	"executive/std",
	"aura/std",
	"indices/std",
	"primitives/std",
	"sr-primitives/std",
	"system/std",
	"timestamp/std",
	"sudo/std",
	"version/std",
	"serde",
	"safe-mix/std",
	"consensus-aura/std",
	"offchain-primitives/std",
	"substrate-session/std",
	"casper/std",
	"casper-primitives/std",
	"session/std",
]
no_std = []
