[package]
name = "ssz"
version = "0.1.2"
authors = ["Parity Team <admin@parity.io>", "Wei Tang <hi@that.world>", "Paul Hauner <paul@paulhauner.com>"]
license-file = "Apache-2.0"
description = "Simple serialization implementation"
edition = "2018"

[dependencies]
primitive-types = { version = "0.4", default-features = false }
codec-io = { version = "0.2", path = "../codec-io", default-features = false }
bm-le = "0.2"
generic-array = "0.12"
typenum = "1.10"
digest = "0.8"

[dev-dependencies]
sha2 = "0.8"
