[package]
name = "ssz"
version = "0.2.0"
authors = ["Parity Team <admin@parity.io>", "Wei Tang <hi@that.world>", "Paul Hauner <paul@paulhauner.com>"]
license = "Apache-2.0"
description = "Simple serialization implementation"
edition = "2018"

[dependencies]
primitive-types = { version = "0.4", default-features = false }
bm-le = "0.10"
generic-array = "0.12"
vecarray = "0.1"
typenum = "1.10"
digest = "0.8"
ssz-derive = { version = "0.2", path = "derive", optional = true }

[dev-dependencies]
sha2 = "0.8"

[features]
default = ["std", "derive"]
std = ["primitive-types/std", "bm-le/std", "vecarray/std"]
derive = ["ssz-derive"]
