[package]
name = "substrate-casper-primitives"
version = "0.1.0"
authors = ["Wei Tang <hi@that.world>"]
edition = "2018"

[dependencies]
primitives = { package = "sp-core", git = "https://github.com/paritytech/substrate", default-features = false }
app-crypto = { package = "sc-application-crypto", git = "https://github.com/paritytech/substrate", default-features = false }
parity-scale-codec = { version = "1.0", default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate" }
sr-primitives = { package = "sp-runtime", git = "https://github.com/paritytech/substrate", default-features = false }

[features]
std = ["primitives/std", "app-crypto/std", "parity-scale-codec/std", "sr-primitives/std"]
default = ["std"]
