[package]
name = "ssz-derive"
version = "0.1.2"
authors = ["Parity Technologies <admin@parity.io>"]
license = "Apache-2.0"
description = "Derive function for simple serialization"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15", features = ["extra-traits"] }
quote = "0.6"
deriving = "0.1"

[dev-dependencies]
ssz = { version = "0.1", path = ".." }
