[package]
name = "ssz-derive"
version = "0.2.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "Apache-2.0"
description = "Derive function for simple serialization"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15", features = ["extra-traits"] }
proc-macro2 = "0.4"
quote = "0.6"
deriving = "0.1"

[dev-dependencies]
ssz = { version = "0.2", path = ".." }
generic-array = "0.12"
typenum = "1.10"
