[package]
name = "shasper-crypto"
version = "0.1.0"
authors = ["Wei Tang <hi@that.world>"]

[dependencies]
bls-aggregates = { git = "https://github.com/sorpaas/signature-schemes", default-features = false }

[features]
default = ["std"]
std = [
	"bls-aggregates/std",
]
